@file:Suppress("ClassName", "ktlint:standard:filename")

package com.github.hubvd.odootools.libgit.legacy

enum class git_status_opt_t(val value: Int) {
    GIT_STATUS_OPT_INCLUDE_UNTRACKED(1 shl 0),
    GIT_STATUS_OPT_INCLUDE_IGNORED(1 shl 1),
    GIT_STATUS_OPT_INCLUDE_UNMODIFIED(1 shl 2),
    GIT_STATUS_OPT_EXCLUDE_SUBMODULES(1 shl 3),
    GIT_STATUS_OPT_RECURSE_UNTRACKED_DIRS(1 shl 4),
    GIT_STATUS_OPT_DISABLE_PATHSPEC_MATCH(1 shl 5),
    GIT_STATUS_OPT_RECURSE_IGNORED_DIRS(1 shl 6),
    GIT_STATUS_OPT_RENAMES_HEAD_TO_INDEX(1 shl 7),
    GIT_STATUS_OPT_RENAMES_INDEX_TO_WORKDIR(1 shl 8),
    GIT_STATUS_OPT_SORT_CASE_SENSITIVELY(1 shl 9),
    GIT_STATUS_OPT_SORT_CASE_INSENSITIVELY(1 shl 10),
    GIT_STATUS_OPT_RENAMES_FROM_REWRITES(1 shl 11),
    GIT_STATUS_OPT_NO_REFRESH(1 shl 12),
    GIT_STATUS_OPT_UPDATE_INDEX(1 shl 13),
    GIT_STATUS_OPT_INCLUDE_UNREADABLE(1 shl 14),
    GIT_STATUS_OPT_INCLUDE_UNREADABLE_AS_UNTRACKED(1 shl 15),
}
