#!/usr/bin/fish

set remote $argv[1]
set url $argv[2]

function fail
  echo $argv 2>&1
  exit 1
end

if test $remote = "origin"
  fail "Can't push to origin"
end

if string match -q '*github.com/odoo/*' $url
  fail "Can't push to github.com/odoo/"
end

if test "$(worktree base)" = "$(git rev-parse --abbrev-ref HEAD)"
  fail "Can't push to a base branch"
end
