#!/usr/bin/fish

set remote $argv[1]
set url $argv[2]

function fail
  echo $argv 2>&1
  exit 1
end

if test $remote = "origin"
  fail "Can't push to origin"
end

if string match -q '*github.com/odoo/*' $url
  fail "Can't push to github.com/odoo/"
end

set local_branch (git rev-parse --abbrev-ref HEAD)

if contains "$local_branch" (workspace -lv)
  fail "Can't push to $local_branch"
end
